POST http://localhost:8000/api/v1/members
Content-Type: application/json

{
  "memberBirth": "2025-05-01",
  "memberEmail": "nane@naver.com",
  "memberId": "javame",
  "memberMobile": "010-1234-5678",
  "memberName": "홍길동",
  "memberPassword": "password",
  "memberSex": "M"
}

###
GET http://localhost:10256/api/v1/members/jjyeonplt

###
